import { Alert } from '@/types/fraud';

export const DEMO_ALERTS: Alert[] = [
  {
    id: 'alt-001',
    alertNumber: 'ALT-2026-1049',
    title: 'Circular Fund Movement Loop Detected',
    description: 'A circular flow of ₹11,80,000 was identified across 3 corporate entities (Apex Logistics → Vikramaditya Traders → BlueHorizon Consulting → Apex Logistics) within 2.5 hours.',
    typology: 'CIRCULAR_ROUTING',
    severity: 'CRITICAL',
    status: 'NEW',
    entityId: 'ENT-8821',
    entityName: 'Apex Logistics Pvt Ltd',
    accountId: 'ACC-HDFC-9912',
    amountRupees: 1180000,
    timestamp: '2026-08-18T16:45:00Z',
    indicators: [
      'Zero commercial underlying purpose identified',
      '3-node closed topology completed in 148 minutes',
      'Loss on round-trip < 1.2% (classic layering signature)',
    ],
  },
  {
    id: 'alt-002',
    alertNumber: 'ALT-2026-1048',
    title: 'Rapid Transaction Velocity & Immediate Mule Dispersal',
    description: 'High-velocity dispersal of ₹8,90,000 received by Vikramaditya Traders split into 4 beneficiary accounts under ₹2,50,000 in under 8 minutes.',
    typology: 'RAPID_VELOCITY',
    severity: 'CRITICAL',
    status: 'INVESTIGATING',
    entityId: 'ENT-4109',
    entityName: 'Vikramaditya Traders',
    accountId: 'ACC-ICICI-4410',
    amountRupees: 890000,
    timestamp: '2026-08-18T16:39:00Z',
    indicators: [
      'Account retention time < 4 minutes',
      'Immediate fan-out ratio 1:4',
      'Beneficiaries newly opened accounts (< 45 days)',
    ],
  },
  {
    id: 'alt-003',
    alertNumber: 'ALT-2026-1047',
    title: 'Multi-Account Sub-₹50k Structuring Pattern',
    description: 'Series of 18 UPI transfers clustered precisely between ₹49,000 and ₹49,800 sent to Zenith Global Merchants avoiding CTR threshold of ₹50,000.',
    typology: 'STRUCTURING',
    severity: 'HIGH',
    status: 'NEW',
    entityId: 'ENT-2019',
    entityName: 'Zenith Global Merchants',
    accountId: 'ACC-SBI-9901',
    amountRupees: 887400,
    timestamp: '2026-08-18T15:58:00Z',
    indicators: [
      '18 distinct UPI senders with shared IP ranges',
      'All transfer values strictly 98-99.6% of threshold',
      'Aggregated into single merchant current account',
    ],
  },
  {
    id: 'alt-004',
    alertNumber: 'ALT-2026-1046',
    title: 'Direct Flow into Unregulated Offshore Crypto Desk',
    description: 'Identified mule account ACC-SBI-1082 initiating exit transfer to flagged crypto P2P liquidity aggregator desk.',
    typology: 'MULE_NETWORK',
    severity: 'CRITICAL',
    status: 'INVESTIGATING',
    entityId: 'ENT-7731',
    entityName: 'Ramesh K. (Mule Node)',
    accountId: 'ACC-SBI-1082',
    amountRupees: 245000,
    timestamp: '2026-08-18T13:28:00Z',
    indicators: [
      'Account holder socio-economic profile mismatch',
      'Zero prior domestic utility history',
      'Direct hop into known illicit exit wallet bridge',
    ],
  },
  {
    id: 'alt-005',
    alertNumber: 'ALT-2026-1045',
    title: 'Dormant Corporate Account Sudden Spike',
    description: 'Account ACC-KOTAK-3301 with zero activity for 11 months suddenly routed ₹32,00,000 in turnover over 48 hours.',
    typology: 'DORMANT_SPIKE',
    severity: 'HIGH',
    status: 'INVESTIGATING',
    entityId: 'ENT-3301',
    entityName: 'BlueHorizon Consulting',
    accountId: 'ACC-KOTAK-3301',
    amountRupees: 3200000,
    timestamp: '2026-08-18T11:15:00Z',
    indicators: [
      '330-day inactivity baseline broken',
      'Turnover 42x historic monthly average',
      'Registered GST number suspended',
    ],
  },
  {
    id: 'alt-006',
    alertNumber: 'ALT-2026-1044',
    title: 'High-Risk Counterparty Adjacency & Shell Cluster',
    description: 'Interaction detected between Orbit FinTech Services and sanctioned shell company entity list.',
    typology: 'HIGH_RISK_INTERACTION',
    severity: 'MEDIUM',
    status: 'RESOLVED',
    entityId: 'ENT-7719',
    entityName: 'Orbit FinTech Services',
    accountId: 'ACC-YES-7719',
    amountRupees: 670000,
    timestamp: '2026-08-18T09:40:00Z',
    indicators: [
      'Shared director DIN with 6 dissolved shell entities',
      'Virtual office address matching known fraud cluster',
    ],
  },
];
