import { Entity } from '@/types/fraud';

export const DEMO_ENTITIES: Entity[] = [
  {
    id: 'ENT-8821',
    name: 'Apex Logistics Pvt Ltd',
    type: 'SHELL_COMPANY',
    registrationNumber: 'U60200MH2021PTC369182',
    taxIdentifier: 'AABCA8821K',
    riskScore: 94,
    riskLevel: 'CRITICAL',
    transactionCount: 428,
    totalVolumeRupees: 48500000,
    alertCount: 7,
    status: 'UNDER_INVESTIGATION',
    accountsCount: 3,
    primaryJurisdiction: 'Maharashtra (Mumbai)',
    flags: ['Carousel Fraud Hub', 'Layering Originator', 'Suspended GST'],
  },
  {
    id: 'ENT-4109',
    name: 'Vikramaditya Traders',
    type: 'MULE_AGGREGATOR',
    registrationNumber: 'U51909DL2022PTC401928',
    taxIdentifier: 'BCDPV4109M',
    riskScore: 91,
    riskLevel: 'CRITICAL',
    transactionCount: 312,
    totalVolumeRupees: 31200000,
    alertCount: 5,
    status: 'FLAGGED',
    accountsCount: 2,
    primaryJurisdiction: 'Delhi NCR',
    flags: ['Rapid Dispersal Hub', 'Mule Feeder Account'],
  },
  {
    id: 'ENT-3301',
    name: 'BlueHorizon Consulting',
    type: 'SHELL_COMPANY',
    registrationNumber: 'U74140KA2020PTC281900',
    taxIdentifier: 'AAECB3301P',
    riskScore: 86,
    riskLevel: 'CRITICAL',
    transactionCount: 184,
    totalVolumeRupees: 28400000,
    alertCount: 4,
    status: 'UNDER_INVESTIGATION',
    accountsCount: 2,
    primaryJurisdiction: 'Karnataka (Bengaluru)',
    flags: ['Dormant Account Spike', 'Circular Routing Return Leg'],
  },
  {
    id: 'ENT-7731',
    name: 'Ramesh K. (Mule Node Alpha)',
    type: 'INDIVIDUAL',
    taxIdentifier: 'BRRPK7731N',
    riskScore: 89,
    riskLevel: 'CRITICAL',
    transactionCount: 64,
    totalVolumeRupees: 4200000,
    alertCount: 3,
    status: 'FROZEN',
    accountsCount: 2,
    primaryJurisdiction: 'Maharashtra (Thane)',
    flags: ['Mule Identity', 'Crypto Bridge Exit', 'Incongruent Turnover'],
  },
  {
    id: 'ENT-2019',
    name: 'Zenith Global Merchants',
    type: 'HIGH_RISK_MERCHANT',
    registrationNumber: 'U51100GJ2023PTC192841',
    taxIdentifier: 'AAGCZ2019R',
    riskScore: 78,
    riskLevel: 'HIGH',
    transactionCount: 1240,
    totalVolumeRupees: 62000000,
    alertCount: 6,
    status: 'FLAGGED',
    accountsCount: 4,
    primaryJurisdiction: 'Gujarat (Surat)',
    flags: ['Structuring Aggregator', 'High-Frequency Burst Receivals'],
  },
  {
    id: 'ENT-7719',
    name: 'Orbit FinTech Services',
    type: 'BUSINESS',
    registrationNumber: 'U72900TG2019PTC132890',
    taxIdentifier: 'AAFCO7719Q',
    riskScore: 68,
    riskLevel: 'HIGH',
    transactionCount: 940,
    totalVolumeRupees: 89000000,
    alertCount: 2,
    status: 'ACTIVE',
    accountsCount: 5,
    primaryJurisdiction: 'Telangana (Hyderabad)',
    flags: ['High Risk Adjacency', 'Layering Intermediary'],
  },
  {
    id: 'ENT-6612',
    name: 'Kaveri Agro Industries',
    type: 'BUSINESS',
    registrationNumber: 'U01111TN2018PTC099182',
    taxIdentifier: 'AABCK6612J',
    riskScore: 38,
    riskLevel: 'MEDIUM',
    transactionCount: 310,
    totalVolumeRupees: 18000000,
    alertCount: 1,
    status: 'ACTIVE',
    accountsCount: 2,
    primaryJurisdiction: 'Tamil Nadu (Coimbatore)',
    flags: ['Seasonal High Turnover'],
  },
];
