import { Investigation } from '@/types/fraud';

export const DEMO_INVESTIGATIONS: Investigation[] = [
  {
    id: 'case-001',
    caseNumber: 'CASE-2026-0881',
    title: 'Syndicate Layering & Mule Ring Alpha',
    typology: 'Mule Aggregation & Circular Laundering',
    priority: 'URGENT',
    riskScore: 95,
    riskLevel: 'CRITICAL',
    assignedInvestigator: 'Agent Kiddo (Lead)',
    lastUpdated: '2026-08-18T16:48:00Z',
    status: 'UNDER_REVIEW',
    entityCount: 12,
    flaggedAmountRupees: 48500000,
    description: 'Multi-jurisdiction laundering ring operating across Mumbai, Delhi, and Bengaluru routing funds through shell companies into P2P crypto gateways.',
  },
  {
    id: 'case-002',
    caseNumber: 'CASE-2026-0879',
    title: 'Circular Fund Movement & Carousel GST Fraud',
    typology: 'Carousel Tax Fraud & Invoice Circularity',
    priority: 'HIGH',
    riskScore: 88,
    riskLevel: 'CRITICAL',
    assignedInvestigator: 'Investigator S. Iyer',
    lastUpdated: '2026-08-18T14:30:00Z',
    status: 'OPEN',
    entityCount: 6,
    flaggedAmountRupees: 28400000,
    description: 'Closed-loop fund movement between Apex Logistics and BlueHorizon Consulting generating artificial transaction volume for tax evasion.',
  },
  {
    id: 'case-003',
    caseNumber: 'CASE-2026-0865',
    title: 'Structuring & High-Velocity Micro-Payments Ring',
    typology: 'Smurfing / Structuring under ₹50,000',
    priority: 'HIGH',
    riskScore: 79,
    riskLevel: 'HIGH',
    assignedInvestigator: 'Analyst R. Deshmukh',
    lastUpdated: '2026-08-18T11:20:00Z',
    status: 'UNDER_REVIEW',
    entityCount: 19,
    flaggedAmountRupees: 18200000,
    description: 'Syndicated UPI micro-deposits under ₹50,000 sent from 18 accounts aggregated into single merchant account in Surat.',
  },
  {
    id: 'case-004',
    caseNumber: 'CASE-2026-0842',
    title: 'Suspicious High-Risk Merchant Hub',
    typology: 'High-Risk Gateway Layering',
    priority: 'MEDIUM',
    riskScore: 64,
    riskLevel: 'HIGH',
    assignedInvestigator: 'Investigator P. Nambiar',
    lastUpdated: '2026-08-17T18:00:00Z',
    status: 'EVIDENCE_SUBMITTED',
    entityCount: 4,
    flaggedAmountRupees: 12500000,
    description: 'Payment gateway account showing excessive chargeback and unauthorized card testing transactions.',
  },
  {
    id: 'case-005',
    caseNumber: 'CASE-2026-0810',
    title: 'Dormant Corporate Takeover Syndicate',
    typology: 'Identity Theft & Account Hijacking',
    priority: 'URGENT',
    riskScore: 91,
    riskLevel: 'CRITICAL',
    assignedInvestigator: 'Agent Kiddo (Lead)',
    lastUpdated: '2026-08-16T15:40:00Z',
    status: 'CLOSED_CONFIRMED',
    entityCount: 8,
    flaggedAmountRupees: 34000000,
    description: 'Confirmed hijacking of suspended private limited shell entities with forged director KYC.',
  },
];
