import { NetworkGraphData } from '@/types/fraud';

export const DEMO_NETWORK_GRAPH: NetworkGraphData = {
  nodes: [
    {
      id: 'ENT-8821',
      label: 'Apex Logistics Pvt Ltd',
      sublabel: 'Shell Company (Hub)',
      type: 'ENTITY',
      riskScore: 94,
      riskLevel: 'CRITICAL',
      isFlagged: true,
    },
    {
      id: 'ACC-HDFC-9912',
      label: 'HDFC Current - 9912',
      sublabel: 'Primary Layering Account',
      type: 'ACCOUNT',
      riskScore: 92,
      riskLevel: 'CRITICAL',
      isFlagged: true,
    },
    {
      id: 'TXN-2026-0891',
      label: 'RTGS ₹8.90L',
      sublabel: 'High Velocity Transfer',
      type: 'TRANSACTION',
      riskScore: 92,
      riskLevel: 'CRITICAL',
      isFlagged: true,
    },
    {
      id: 'ACC-ICICI-4410',
      label: 'ICICI Current - 4410',
      sublabel: 'Dispersal Aggregator',
      type: 'ACCOUNT',
      riskScore: 88,
      riskLevel: 'CRITICAL',
      isFlagged: true,
    },
    {
      id: 'ENT-4109',
      label: 'Vikramaditya Traders',
      sublabel: 'Mule Aggregator Node',
      type: 'ENTITY',
      riskScore: 91,
      riskLevel: 'CRITICAL',
      isFlagged: true,
    },
    {
      id: 'TXN-2026-0892',
      label: 'IMPS ₹2.50L',
      sublabel: 'Mule Payout 1',
      type: 'TRANSACTION',
      riskScore: 88,
      riskLevel: 'CRITICAL',
      isFlagged: true,
    },
    {
      id: 'ACC-SBI-1082',
      label: 'SBI Savings - 1082',
      sublabel: 'Mule Account Alpha',
      type: 'ACCOUNT',
      riskScore: 89,
      riskLevel: 'CRITICAL',
      isFlagged: true,
    },
    {
      id: 'ENT-7731',
      label: 'Ramesh K.',
      sublabel: 'Mule Individual Node',
      type: 'ENTITY',
      riskScore: 89,
      riskLevel: 'CRITICAL',
      isFlagged: true,
    },
    {
      id: 'ACC-KOTAK-3301',
      label: 'Kotak Current - 3301',
      sublabel: 'Dormant Spiking Account',
      type: 'ACCOUNT',
      riskScore: 86,
      riskLevel: 'CRITICAL',
      isFlagged: true,
    },
    {
      id: 'ENT-3301',
      label: 'BlueHorizon Consulting',
      sublabel: 'Loop Closing Node',
      type: 'ENTITY',
      riskScore: 86,
      riskLevel: 'CRITICAL',
      isFlagged: true,
    },
  ],
  edges: [
    {
      id: 'e1',
      source: 'ENT-8821',
      target: 'ACC-HDFC-9912',
      label: 'Controls Account',
      type: 'OWNS_ACCOUNT',
    },
    {
      id: 'e2',
      source: 'ACC-HDFC-9912',
      target: 'TXN-2026-0891',
      label: 'Sends ₹8,90,000',
      amountRupees: 890000,
      type: 'TRANSFERS_TO',
    },
    {
      id: 'e3',
      source: 'TXN-2026-0891',
      target: 'ACC-ICICI-4410',
      label: 'Credited to',
      amountRupees: 890000,
      type: 'TRANSFERS_TO',
    },
    {
      id: 'e4',
      source: 'ENT-4109',
      target: 'ACC-ICICI-4410',
      label: 'Controls Account',
      type: 'OWNS_ACCOUNT',
    },
    {
      id: 'e5',
      source: 'ACC-ICICI-4410',
      target: 'TXN-2026-0892',
      label: 'Splits ₹2,50,000',
      amountRupees: 250000,
      type: 'TRANSFERS_TO',
    },
    {
      id: 'e6',
      source: 'TXN-2026-0892',
      target: 'ACC-SBI-1082',
      label: 'Credited to Mule',
      amountRupees: 250000,
      type: 'TRANSFERS_TO',
    },
    {
      id: 'e7',
      source: 'ENT-7731',
      target: 'ACC-SBI-1082',
      label: 'Registered Holder',
      type: 'OWNS_ACCOUNT',
    },
    {
      id: 'e8',
      source: 'ACC-HDFC-9912',
      target: 'ACC-KOTAK-3301',
      label: 'Circular Flow ₹11.8L',
      amountRupees: 1180000,
      type: 'TRANSFERS_TO',
    },
    {
      id: 'e9',
      source: 'ENT-3301',
      target: 'ACC-KOTAK-3301',
      label: 'Controls Account',
      type: 'OWNS_ACCOUNT',
    },
  ],
};
