import { Transaction } from '@/types/fraud';

export const DEMO_TRANSACTIONS: Transaction[] = [
  {
    id: 'txn-001',
    referenceNumber: 'TXN-2026-0891',
    timestamp: '2026-08-18T16:42:10Z',
    senderAccount: 'ACC-HDFC-9912',
    senderEntityName: 'Apex Logistics Pvt Ltd',
    senderEntityId: 'ENT-8821',
    receiverAccount: 'ACC-ICICI-4410',
    receiverEntityName: 'Vikramaditya Traders',
    receiverEntityId: 'ENT-4109',
    amount: 890000,
    currency: 'INR',
    channel: 'RTGS',
    riskScore: 92,
    riskLevel: 'CRITICAL',
    status: 'FLAGGED',
    flags: ['Rapid Dispersal Flow', 'High-Risk Counterparty Adjacency'],
    narrative: 'Intercompany settlement - suspicious immediate routing',
  },
  {
    id: 'txn-002',
    referenceNumber: 'TXN-2026-0892',
    timestamp: '2026-08-18T16:38:45Z',
    senderAccount: 'ACC-ICICI-4410',
    senderEntityName: 'Vikramaditya Traders',
    senderEntityId: 'ENT-4109',
    receiverAccount: 'ACC-SBI-1082',
    receiverEntityName: 'Ramesh K. (Mule Node)',
    receiverEntityId: 'ENT-7731',
    amount: 250000,
    currency: 'INR',
    channel: 'IMPS',
    riskScore: 88,
    riskLevel: 'CRITICAL',
    status: 'FLAGGED',
    flags: ['Mule Account Characteristic', 'Structuring Pattern'],
    narrative: 'Consulting fees split payout 1/4',
  },
  {
    id: 'txn-003',
    referenceNumber: 'TXN-2026-0893',
    timestamp: '2026-08-18T16:35:12Z',
    senderAccount: 'ACC-ICICI-4410',
    senderEntityName: 'Vikramaditya Traders',
    senderEntityId: 'ENT-4109',
    receiverAccount: 'ACC-AXIS-7741',
    receiverEntityName: 'Sunil Verma',
    receiverEntityId: 'ENT-9914',
    amount: 250000,
    currency: 'INR',
    channel: 'IMPS',
    riskScore: 84,
    riskLevel: 'CRITICAL',
    status: 'FLAGGED',
    flags: ['Structuring Pattern', 'Velocity Anomaly'],
    narrative: 'Consulting fees split payout 2/4',
  },
  {
    id: 'txn-004',
    referenceNumber: 'TXN-2026-0894',
    timestamp: '2026-08-18T16:20:00Z',
    senderAccount: 'ACC-KOTAK-3301',
    senderEntityName: 'BlueHorizon Consulting',
    senderEntityId: 'ENT-3301',
    receiverAccount: 'ACC-HDFC-9912',
    receiverEntityName: 'Apex Logistics Pvt Ltd',
    receiverEntityId: 'ENT-8821',
    amount: 1245000,
    currency: 'INR',
    channel: 'NEFT',
    riskScore: 78,
    riskLevel: 'HIGH',
    status: 'UNDER_REVIEW',
    flags: ['Circular Flow Initiation', 'Dormant Account Spike'],
    narrative: 'Advance contract settlement',
  },
  {
    id: 'txn-005',
    referenceNumber: 'TXN-2026-0895',
    timestamp: '2026-08-18T15:55:18Z',
    senderAccount: 'ACC-PAYTM-5520',
    senderEntityName: 'Aarav Sharma',
    senderEntityId: 'ENT-5520',
    receiverAccount: 'ACC-SBI-9901',
    receiverEntityName: 'Zenith Global Merchants',
    receiverEntityId: 'ENT-2019',
    amount: 49500,
    currency: 'INR',
    channel: 'UPI',
    riskScore: 74,
    riskLevel: 'HIGH',
    status: 'FLAGGED',
    flags: ['Sub-50k Structuring', 'High Frequency Burst'],
    narrative: 'Vendor payment',
  },
  {
    id: 'txn-006',
    referenceNumber: 'TXN-2026-0896',
    timestamp: '2026-08-18T15:52:04Z',
    senderAccount: 'ACC-PAYTM-5520',
    senderEntityName: 'Aarav Sharma',
    senderEntityId: 'ENT-5520',
    receiverAccount: 'ACC-SBI-9901',
    receiverEntityName: 'Zenith Global Merchants',
    receiverEntityId: 'ENT-2019',
    amount: 49200,
    currency: 'INR',
    channel: 'UPI',
    riskScore: 74,
    riskLevel: 'HIGH',
    status: 'FLAGGED',
    flags: ['Sub-50k Structuring', 'Repeated Beneficiary'],
    narrative: 'Invoice clearing',
  },
  {
    id: 'txn-007',
    referenceNumber: 'TXN-2026-0897',
    timestamp: '2026-08-18T15:30:22Z',
    senderAccount: 'ACC-PNB-6612',
    senderEntityName: 'Kaveri Agro Industries',
    senderEntityId: 'ENT-6612',
    receiverAccount: 'ACC-HDFC-1120',
    receiverEntityName: 'Shree Balaji Traders',
    receiverEntityId: 'ENT-1120',
    amount: 340000,
    currency: 'INR',
    channel: 'NEFT',
    riskScore: 48,
    riskLevel: 'MEDIUM',
    status: 'COMPLETED',
    flags: ['Minor Deviation from Baseline'],
    narrative: 'Seasonal harvest purchase',
  },
  {
    id: 'txn-008',
    referenceNumber: 'TXN-2026-0898',
    timestamp: '2026-08-18T15:10:05Z',
    senderAccount: 'ACC-BOB-9981',
    senderEntityName: 'Naveen Enterprises',
    senderEntityId: 'ENT-9981',
    receiverAccount: 'ACC-CANARA-4011',
    receiverEntityName: 'Southern Steel Hub',
    receiverEntityId: 'ENT-4011',
    amount: 75000,
    currency: 'INR',
    channel: 'IMPS',
    riskScore: 22,
    riskLevel: 'LOW',
    status: 'COMPLETED',
    flags: [],
    narrative: 'Raw material procurement',
  },
  {
    id: 'txn-009',
    referenceNumber: 'TXN-2026-0899',
    timestamp: '2026-08-18T14:45:10Z',
    senderAccount: 'ACC-HDFC-9912',
    senderEntityName: 'Apex Logistics Pvt Ltd',
    senderEntityId: 'ENT-8821',
    receiverAccount: 'ACC-KOTAK-3301',
    receiverEntityName: 'BlueHorizon Consulting',
    receiverEntityId: 'ENT-3301',
    amount: 1180000,
    currency: 'INR',
    channel: 'RTGS',
    riskScore: 94,
    riskLevel: 'CRITICAL',
    status: 'BLOCKED',
    flags: ['Circular Flow Closing Leg', 'Layering Round-Trip'],
    narrative: 'Re-routing fund return',
  },
  {
    id: 'txn-010',
    referenceNumber: 'TXN-2026-0900',
    timestamp: '2026-08-18T14:15:33Z',
    senderAccount: 'ACC-INDUS-8820',
    senderEntityName: 'Priya Sundaram',
    senderEntityId: 'ENT-8820',
    receiverAccount: 'ACC-AXIS-2009',
    receiverEntityName: 'Aditi Fashion Hub',
    receiverEntityId: 'ENT-2009',
    amount: 18500,
    currency: 'INR',
    channel: 'UPI',
    riskScore: 12,
    riskLevel: 'LOW',
    status: 'COMPLETED',
    flags: [],
    narrative: 'Retail order #44912',
  },
  {
    id: 'txn-011',
    referenceNumber: 'TXN-2026-0901',
    timestamp: '2026-08-18T13:50:11Z',
    senderAccount: 'ACC-YES-7719',
    senderEntityName: 'Orbit FinTech Services',
    senderEntityId: 'ENT-7719',
    receiverAccount: 'ACC-HDFC-9912',
    receiverEntityName: 'Apex Logistics Pvt Ltd',
    receiverEntityId: 'ENT-8821',
    amount: 670000,
    currency: 'INR',
    channel: 'IMPS',
    riskScore: 68,
    riskLevel: 'HIGH',
    status: 'UNDER_REVIEW',
    flags: ['Sudden Volume Burst'],
    narrative: 'Merchant settlement',
  },
  {
    id: 'txn-012',
    referenceNumber: 'TXN-2026-0902',
    timestamp: '2026-08-18T13:25:40Z',
    senderAccount: 'ACC-SBI-1082',
    senderEntityName: 'Ramesh K. (Mule Node)',
    senderEntityId: 'ENT-7731',
    receiverAccount: 'ACC-CRYPTO-GATE',
    receiverEntityName: 'Offshore P2P Exchange Desk',
    receiverEntityId: 'ENT-0099',
    amount: 245000,
    currency: 'INR',
    channel: 'IMPS',
    riskScore: 96,
    riskLevel: 'CRITICAL',
    status: 'BLOCKED',
    flags: ['Direct Crypto Cash-Out', 'Mule Exit Point'],
    narrative: 'P2P Order 99182',
  },
  {
    id: 'txn-013',
    referenceNumber: 'TXN-2026-0903',
    timestamp: '2026-08-18T12:40:19Z',
    senderAccount: 'ACC-HDFC-3321',
    senderEntityName: 'Tata Tele Solutions',
    senderEntityId: 'ENT-3321',
    receiverAccount: 'ACC-SBI-8812',
    receiverEntityName: 'Reliance Comms',
    receiverEntityId: 'ENT-8812',
    amount: 5400000,
    currency: 'INR',
    channel: 'RTGS',
    riskScore: 18,
    riskLevel: 'LOW',
    status: 'COMPLETED',
    flags: [],
    narrative: 'Inter-carrier lease line dues',
  },
  {
    id: 'txn-014',
    referenceNumber: 'TXN-2026-0904',
    timestamp: '2026-08-18T12:10:00Z',
    senderAccount: 'ACC-IDFC-4491',
    senderEntityName: 'Kiran Enterprises',
    senderEntityId: 'ENT-4491',
    receiverAccount: 'ACC-ICICI-4410',
    receiverEntityName: 'Vikramaditya Traders',
    receiverEntityId: 'ENT-4109',
    amount: 450000,
    currency: 'INR',
    channel: 'NEFT',
    riskScore: 72,
    riskLevel: 'HIGH',
    status: 'FLAGGED',
    flags: ['Shell Co Pattern', 'Layering Aggregation'],
    narrative: 'Material advance',
  },
  {
    id: 'txn-015',
    referenceNumber: 'TXN-2026-0905',
    timestamp: '2026-08-18T11:45:12Z',
    senderAccount: 'ACC-AXIS-9932',
    senderEntityName: 'Mehra Exports',
    senderEntityId: 'ENT-9932',
    receiverAccount: 'ACC-PNB-6612',
    receiverEntityName: 'Kaveri Agro Industries',
    receiverEntityId: 'ENT-6612',
    amount: 195000,
    currency: 'INR',
    channel: 'IMPS',
    riskScore: 35,
    riskLevel: 'MEDIUM',
    status: 'COMPLETED',
    flags: [],
    narrative: 'Packaging invoice #112',
  },
];
